export enum EButtonTypes {
  DEALS = 'DEALS',
  CONDITION = 'CONDITION',
  ETA = 'ETA',
  GREEN = 'GREEN',
  PACKAGING = 'PACKAGING',
  RESTRICTIONS = 'RESTRICTIONS',
  ROCKET = 'ROCKET',
  WARRANTY = 'WARRANTY'
}
